# Generated by Django 5.1.6 on 2025-04-09 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(choices=[('location1', 'Location 1'), ('location2', 'Location 2')], max_length=50)),
                ('drop', models.CharField(choices=[('location1', 'Location 1'), ('location2', 'Location 2')], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('passengers', models.PositiveIntegerField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('suggestion', models.TextField(default='No suggestion provided')),
            ],
        ),
    ]
