# Generated by Django 5.1.6 on 2025-04-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_drop_booking_drop_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drop_location',
            field=models.CharField(choices=[('Boys Hostel', 'Boys Hostel'), ('Girls Hostel', 'Girls Hostel'), ('Main Gate', 'Main Gate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(choices=[('Boys Hostel', 'Boys Hostel'), ('Girls Hostel', 'Girls Hostel'), ('Main Gate', 'Main Gate')], max_length=50),
        ),
    ]
